// schemes.js
// Smile Financial Solution - AI Funding Consultant Pro
// Verified Government Schemes Database - Production Ready

const GOVERNMENT_SCHEMES = [
  // ======================== STARTUP SCHEMES ========================
  {
    id: "startup_india_seed_fund",
    schemeName: "Startup India Seed Fund Scheme",
    alternativeNames: ["SISFS", "Seed Fund"],
    launchYear: 2021,
    ministry: "Ministry of Commerce and Industry",
    department: "DPIIT",
    officialPortal: "www.startupindia.gov.in",
    officialGuideline: "https://www.startupindia.gov.in/content/sih/en/seedfund.html",
    objective: "Financial support to startups for proof of concept, prototype development, product trials, and market entry.",
    overview: "The Startup India Seed Fund Scheme aims to provide financial assistance to startups for early-stage funding. It supports startups with up to ₹50 lakh for validation and early traction.",
    category: "Startup",
    sector: "All sectors",
    businessTypes: ["Startup", "Tech", "Innovation", "Product"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "DPIIT-recognized startups, incorporated within 2 years, with innovative business model.",
    whoCannotApply: "Non-DPIIT startups, companies older than 2 years, trading/retail businesses without innovation.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Less than 2 years",
    turnoverRequirement: null,
    investmentRequirement: "Up to ₹50 lakh",
    fundingType: "Grant + Equity",
    loanComponent: null,
    grantComponent: "Up to ₹50 lakh",
    subsidyComponent: null,
    maximumFunding: 5000000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: "Not required",
    processingFees: null,
    requiredDocuments: ["DPIIT Recognition", "Business Plan", "Financial Projections", "KYC", "Incorporation Certificate"],
    optionalDocuments: ["Patent/IP Details", "Technical Validation", "POC Report"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Company Registration", "GST (if applicable)"],
    applicationMode: "Online",
    applicationProcess: "Apply through Startup India portal. Submit pitch deck and proposal. Evaluation by expert committee.",
    approvalProcess: "Expert committee reviews application. Selected startups get funding in tranches.",
    fundReleaseProcess: "Funds released in stages based on milestones achieved.",
    processingTimeline: "60-90 days",
    consultantChecklist: "DPIIT recognition mandatory, strong business plan, clear milestones.",
    customerBenefits: "Early-stage funding without collateral, validation support, mentorship.",
    commonMistakes: "Incomplete business plan, unrealistic projections, not meeting milestones.",
    commonRejectionReasons: "Not DPIIT recognized, weak business model, incomplete application.",
    consultantNotes: "Startup India recognition is the first step. Apply early and keep milestones realistic.",
    customerPitch: "अगर आप एक नया startup हैं और proof of concept ya product launch के लिए funding चाहिए, तो यह scheme आपके लिए है।",
    faq: [
      { q: "क्या मैं इस scheme के लिए apply कर सकता हूँ?", a: "हाँ, अगर आपका startup DPIIT-recognized है और 2 साल से कम पुराना है।" },
      { q: "कितनी funding मिल सकती है?", a: "अधिकतम ₹50 लाख तक।" }
    ],
    relatedSchemes: ["startup_india_recognition", "incubation_scheme"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "startup_india_recognition",
    schemeName: "Startup India Recognition",
    alternativeNames: ["DPIIT Recognition", "Startup Recognition"],
    launchYear: 2016,
    ministry: "Ministry of Commerce and Industry",
    department: "DPIIT",
    officialPortal: "www.startupindia.gov.in",
    officialGuideline: "https://www.startupindia.gov.in/content/sih/en/recognition.html",
    objective: "To provide official recognition to startups and enable them to avail benefits under various schemes.",
    overview: "Startup India Recognition is a certification by DPIIT that validates a business as a startup. It unlocks tax benefits, funding opportunities, and regulatory exemptions.",
    category: "Startup",
    sector: "All sectors",
    businessTypes: ["Startup", "Innovation", "Tech", "Product"],
    entityTypes: ["Private Limited", "LLP", "Partnership"],
    whoCanApply: "Any entity incorporated as a Private Limited, LLP, or Partnership, with innovative business model, and age less than 10 years.",
    whoCannotApply: "Entities older than 10 years, non-innovative businesses, retail/trading without innovation.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Less than 10 years",
    turnoverRequirement: "Less than ₹100 crore",
    investmentRequirement: null,
    fundingType: "Recognition Only",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: null,
    ownContribution: null,
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Incorporation Certificate", "Business Plan", "Financial Statements", "KYC"],
    optionalDocuments: ["Patent/IP", "Client List", "Awards"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Company Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply on Startup India portal with business details and documents.",
    approvalProcess: "DPIIT reviews and grants recognition certificate.",
    fundReleaseProcess: "N/A",
    processingTimeline: "15-30 days",
    consultantChecklist: "Ensure innovation in business model, complete documentation.",
    customerBenefits: "Tax exemptions, priority in government tenders, easier funding access.",
    commonMistakes: "Not providing enough innovation proof, incomplete documentation.",
    commonRejectionReasons: "No innovation, duplicate application, incomplete info.",
    consultantNotes: "Recognition is the foundation for all other startup benefits.",
    customerPitch: "Startup India Recognition सरकार से मान्यता है जो आपको tax benefits और funding opportunities देती है।",
    faq: [
      { q: "Recognition के क्या फायदे हैं?", a: "Tax exemption, funding access, and government tenders में priority." },
      { q: "कितने साल तक valid रहता है?", a: "10 साल या turnover ₹100 crore तक।" }
    ],
    relatedSchemes: ["startup_india_seed_fund", "incubation_scheme"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "incubation_scheme",
    schemeName: "Incubation Scheme (Startup Incubators)",
    alternativeNames: ["Startup Incubation", "Incubator Support"],
    launchYear: 2017,
    ministry: "Ministry of Electronics and IT",
    department: "MeitY",
    officialPortal: "www.startupindia.gov.in",
    officialGuideline: "https://www.startupindia.gov.in/content/sih/en/incubators.html",
    objective: "To promote incubation centers that nurture startups through infrastructure, mentorship, and funding support.",
    overview: "Government supports incubators across India that provide co-working space, mentorship, and seed funding to startups.",
    category: "Startup",
    sector: "All sectors",
    businessTypes: ["Startup", "Tech", "Innovation", "Product"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "Startups registered under any entity type, with a scalable business idea.",
    whoCannotApply: "Non-innovative businesses, trading/retail businesses.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Less than 5 years",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Infrastructure + Mentorship",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: null,
    ownContribution: null,
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Business Plan", "KYC", "Incorporation Certificate"],
    optionalDocuments: ["Patent/IP", "Technical Proof"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Company Registration"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply to recognized incubators. Pitch your idea to incubation manager.",
    approvalProcess: "Incubator reviews and selects startups for incubation.",
    fundReleaseProcess: "N/A",
    processingTimeline: "30-60 days",
    consultantChecklist: "Prepare a strong pitch deck, validate business model.",
    customerBenefits: "Co-working space, mentorship, networking, seed funding access.",
    commonMistakes: "Vague business idea, no market validation.",
    commonRejectionReasons: "Unclear revenue model, no team strength.",
    consultantNotes: "Choose an incubator that aligns with your sector for better support.",
    customerPitch: "अगर आपको workspace, mentorship और networking चाहिए, तो incubation scheme best option है।",
    faq: [
      { q: "Incubator क्या होता है?", a: "A space where startups get office, mentorship, and support to grow." },
      { q: "क्या इसके लिए कोई fee लगती है?", a: "Some incubators charge nominal fees, but many are subsidized." }
    ],
    relatedSchemes: ["startup_india_seed_fund", "startup_india_recognition"],
    lastUpdated: "2025-01-15"
  },
  // ======================== MSME / MANUFACTURING SCHEMES ========================
  {
    id: "pmegp",
    schemeName: "Prime Minister's Employment Generation Programme",
    alternativeNames: ["PMEGP"],
    launchYear: 2008,
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "MSME Ministry",
    officialPortal: "www.kvic.gov.in",
    officialGuideline: "https://www.kvic.gov.in/pmegp",
    objective: "To generate employment through setting up of micro enterprises in rural and urban areas.",
    overview: "PMEGP is a flagship scheme offering subsidy up to 35% for manufacturing and 25% for service sector projects.",
    category: "MSME",
    sector: "All sectors except prohibited industries",
    businessTypes: ["Micro Enterprise", "Manufacturing", "Service", "Food Processing"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "Trust", "Society"],
    whoCanApply: "Any individual above 18 years, with a viable project. Minimum 8th pass.",
    whoCannotApply: "Students with no business experience, defaulters of earlier PMEGP loans.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "New project only",
    turnoverRequirement: null,
    investmentRequirement: "Up to ₹50 lakh (manufacturing), ₹20 lakh (service)",
    fundingType: "Term Loan + Subsidy",
    loanComponent: "Balance amount after subsidy",
    grantComponent: null,
    subsidyComponent: "25% (rural), 35% (urban) for general; 35% (rural), 45% (urban) for special categories",
    maximumFunding: 5000000,
    ownContribution: "5-10%",
    marginMoney: "Subsidy acts as margin money",
    interestInformation: "Bank rate as applicable",
    moratorium: "6-12 months",
    repaymentTenure: "3-7 years",
    collateralRequirement: "No collateral for up to ₹10 lakh, above that as per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Quotations", "Land documents (if owned)", "Category certificate (if applicable)"],
    optionalDocuments: ["Training Certificate", "Experience Letter"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "MSME Registration", "Trade License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through KVIC/KVIB/DIC. Submit project report and documents. Bank appraises and sanctions.",
    approvalProcess: "Project appraised by bank, recommended to KVIC for subsidy approval.",
    fundReleaseProcess: "Loan disbursed by bank, subsidy released after first installment.",
    processingTimeline: "45-90 days",
    consultantChecklist: "Prepare DPR carefully, ensure quotations are genuine, choose feasible project.",
    customerBenefits: "High subsidy, no collateral for small loans, employment generation.",
    commonMistakes: "Overestimating project cost, not meeting margin money requirement.",
    commonRejectionReasons: "Non-viable project, incomplete documents, category mismatch.",
    consultantNotes: "PMEGP is best for first-time entrepreneurs. Focus on rural/urban classification for subsidy.",
    customerPitch: "PMEGP आपको 25% से 45% subsidy के साथ business शुरू करने का सुनहरा अवसर देता है।",
    faq: [
      { q: "PMEGP में कितनी subsidy मिलती है?", a: "Manufacturing में 25% (rural) to 35% (urban), service में 15% to 25%." },
      { q: "क्या मैं PMEGP लोन दोबारा ले सकता हूँ?", a: "No, PMEGP is one-time for each project/entity." }
    ],
    relatedSchemes: ["mudra_yojana", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "mudra_yojana",
    schemeName: "Pradhan Mantri MUDRA Yojana",
    alternativeNames: ["PM MUDRA", "MUDRA Loan"],
    launchYear: 2015,
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    officialPortal: "www.mudra.org.in",
    officialGuideline: "https://www.mudra.org.in/",
    objective: "To fund micro enterprises and small businesses through collateral-free loans.",
    overview: "MUDRA offers loans under three categories: Shishu (up to ₹50,000), Kishor (up to ₹5 lakh), Tarun (up to ₹10 lakh).",
    category: "MSME",
    sector: "All sectors except prohibited",
    businessTypes: ["Micro Enterprise", "Small Business", "Manufacturing", "Service", "Trade", "Agriculture"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited"],
    whoCanApply: "Any individual with a business idea or existing micro enterprise.",
    whoCannotApply: "Large enterprises, defaulters, non-viable businesses.",
    minimumAge: 18,
    maximumAge: 65,
    businessAgeRequirement: "Any, but established businesses preferred",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Working Capital + Term Loan",
    loanComponent: "100% loan (no subsidy)",
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: 1000000,
    ownContribution: null,
    marginMoney: null,
    interestInformation: "Bank rate as applicable (usually 8-14%)",
    moratorium: "Up to 6 months",
    repaymentTenure: "3-5 years",
    collateralRequirement: "No collateral",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Business Plan", "Bank Statement (6 months)", "GST (if applicable)"],
    optionalDocuments: ["Project Report", "Quotations"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["GST (if turnover > ₹40 lakh)", "MSME Registration"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through any bank branch (PSU, private, cooperative). Submit loan application and documents.",
    approvalProcess: "Bank appraises and sanctions based on CIBIL, business viability, and repayment capacity.",
    fundReleaseProcess: "Loan disbursed in full or in tranches based on purpose.",
    processingTimeline: "7-15 days",
    consultantChecklist: "Check CIBIL score, prepare business plan, maintain clean bank statements.",
    customerBenefits: "Collateral-free loans, quick processing, flexible repayment.",
    commonMistakes: "Incomplete KYC, weak business plan, poor CIBIL.",
    commonRejectionReasons: "Low CIBIL, lack of business proof, negative cash flow.",
    consultantNotes: "MUDRA is ideal for small businesses. Start with Shishu and upgrade as you grow.",
    customerPitch: "MUDRA loan बिना collateral के आपके business को ₹10 lakh तक का funding देता है।",
    faq: [
      { q: "MUDRA loan के लिए CIBIL कितना चाहिए?", a: "Generally 650+, but banks may consider on case basis." },
      { q: "क्या मैं MUDRA loan को renew कर सकता हूँ?", a: "Yes, based on repayment history and business growth." }
    ],
    relatedSchemes: ["pmegp", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "cgtmse",
    schemeName: "Credit Guarantee Fund Trust for Micro and Small Enterprises",
    alternativeNames: ["CGTMSE", "Credit Guarantee"],
    launchYear: 2000,
    ministry: "Ministry of MSME",
    department: "SIDBI",
    officialPortal: "www.cgtmse.in",
    officialGuideline: "https://www.cgtmse.in/",
    objective: "To provide guarantee cover to banks for collateral-free lending to MSMEs.",
    overview: "CGTMSE provides guarantee to banks for loans up to ₹2 crore without collateral, reducing risk for lenders and enabling easier credit access for MSMEs.",
    category: "MSME",
    sector: "All sectors",
    businessTypes: ["Micro", "Small", "Manufacturing", "Service", "Trade"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "LLP"],
    whoCanApply: "Any MSME with a viable business, but loan must be sanctioned by a member lending institution.",
    whoCannotApply: "Large enterprises, non-MSME entities, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1-2 years",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Guarantee Cover",
    loanComponent: "Loan sanctioned by bank",
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: 20000000,
    ownContribution: null,
    marginMoney: null,
    interestInformation: "Bank rate + guarantee fee (0.5-2%)",
    moratorium: "As per bank",
    repaymentTenure: "Up to 7 years",
    collateralRequirement: "No collateral (guarantee cover)",
    processingFees: "Bank charges",
    requiredDocuments: ["KYC", "MSME Registration", "Bank Statements", "ITR"],
    optionalDocuments: ["Project Report", "Balance Sheet"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["MSME Registration", "GST"],
    applicationMode: "Through Bank",
    applicationProcess: "Apply to any bank. Bank processes loan and avails CGTMSE guarantee.",
    approvalProcess: "Bank sanctions based on credit appraisal.",
    fundReleaseProcess: "Loan disbursed as per bank norms.",
    processingTimeline: "7-30 days",
    consultantChecklist: "Maintain good credit history, ensure MSME registration is active.",
    customerBenefits: "No collateral, easier loan approval, lower risk for bank.",
    commonMistakes: "Incomplete registration, poor cash flow management.",
    commonRejectionReasons: "Low CIBIL, insufficient business vintage.",
    consultantNotes: "CGTMSE is not a loan scheme but a guarantee mechanism. Always apply through a bank.",
    customerPitch: "CGTMSE के guarantee cover की वजह से आपको बिना collateral के loan मिल सकता है।",
    faq: [
      { q: "क्या CGTMSE guarantee के लिए कोई fee है?", a: "Yes, 0.5% to 2% guarantee fee, usually borne by the borrower." },
      { q: "कितने का loan cover मिलता है?", a: "Up to ₹2 crore per borrower." }
    ],
    relatedSchemes: ["mudra_yojana", "pmegp"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "pm_vishwakarma",
    schemeName: "PM Vishwakarma Yojana",
    alternativeNames: ["PM Vishwakarma"],
    launchYear: 2023,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.pmvishwakarma.gov.in",
    officialGuideline: "https://www.pmvishwakarma.gov.in/",
    objective: "To support traditional artisans and craftspeople with skill upgradation, toolkits, and credit.",
    overview: "PM Vishwakarma Yojana provides recognition, skill training, toolkits, and collateral-free credit up to ₹1 lakh (first tranche) and ₹2 lakh (second tranche) to traditional artisans.",
    category: "MSME",
    sector: "Handicrafts, Traditional Arts, Handloom, Carpentry, Goldsmith, etc.",
    businessTypes: ["Artisan", "Craftsman", "Handicraft", "Traditional Business"],
    entityTypes: ["Sole Proprietorship", "Individual"],
    whoCanApply: "Traditional artisans and craftspeople practicing family-based crafts.",
    whoCannotApply: "Non-artisan business, large enterprises.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Minimum 1 year experience",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Term Loan + Subsidy",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "Interest subsidy",
    maximumFunding: 300000,
    ownContribution: null,
    marginMoney: null,
    interestInformation: "5% interest with government subsidy reducing effective to 0%",
    moratorium: "6 months",
    repaymentTenure: "3 years",
    collateralRequirement: "No collateral",
    processingFees: "None",
    requiredDocuments: ["KYC", "Proof of Craft", "Bank Account", "Aadhaar"],
    optionalDocuments: ["Training Certificate", "Toolkit Receipt"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["None"],
    applicationMode: "Online + Offline",
    applicationProcess: "Register on PM Vishwakarma portal, get recognized, undergo training, receive toolkit, then apply for loan.",
    approvalProcess: "Recognition + training completion → loan eligibility.",
    fundReleaseProcess: "Loan disbursed by bank after training and toolkit.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Ensure artisan recognition, complete training, keep digital records.",
    customerBenefits: "Recognition, skill upgradation, toolkit, and collateral-free loan.",
    commonMistakes: "Not completing training, not maintaining craft proof.",
    commonRejectionReasons: "Craft not recognized, incomplete documentation.",
    consultantNotes: "PM Vishwakarma is for traditional artisans. It's a holistic scheme with recognition, training, and credit.",
    customerPitch: "PM Vishwakarma आपको पारंपरिक कला के लिए recognition, toolkit और 0% interest loan देता है।",
    faq: [
      { q: "कौन-कौन apply कर सकता है?", a: "Traditional artisans like carpenters, blacksmiths, goldsmiths, potters, etc." },
      { q: "कितना loan मिल सकता है?", a: "First tranche ₹1 lakh, second tranche ₹2 lakh (interest-free)." }
    ],
    relatedSchemes: ["pmegp", "mudra_yojana"],
    lastUpdated: "2025-01-15"
  },
  // ======================== AGRICULTURE SCHEMES ========================
  {
    id: "agriculture_infrastructure_fund",
    schemeName: "Agriculture Infrastructure Fund",
    alternativeNames: ["AIF"],
    launchYear: 2020,
    ministry: "Ministry of Agriculture and Farmers' Welfare",
    department: "Department of Agriculture",
    officialPortal: "www.agricultureinfrastructurefund.com",
    officialGuideline: "https://agriinfra.dac.gov.in/",
    objective: "To provide financing for building community agriculture infrastructure including cold storage, warehousing, and processing units.",
    overview: "AIF is a medium to long-term debt financing facility for investment in viable projects for post-harvest management infrastructure and community farming assets.",
    category: "Agriculture",
    sector: "Agriculture, Food Processing, Agri-Infrastructure",
    businessTypes: ["Agri-Infrastructure", "Cold Storage", "Warehousing", "Processing"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship", "FPO"],
    whoCanApply: "Farmers, FPOs, co-operatives, agri-entrepreneurs, startups, and companies.",
    whoCannotApply: "Non-agricultural businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any, but established businesses preferred.",
    turnoverRequirement: null,
    investmentRequirement: "Minimum ₹10 lakh",
    fundingType: "Term Loan + Interest Subvention",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "Interest subvention",
    maximumFunding: 100000000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Base rate - 2% interest subvention (effective ~7-9%)",
    moratorium: "Up to 2 years",
    repaymentTenure: "Up to 10 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Land documents", "Bank Statements", "GST"],
    optionalDocuments: ["Quotations", "Technical Feasibility Report"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "MSME Registration", "FSSAI (if processing)"],
    applicationMode: "Online",
    applicationProcess: "Apply through online portal. Submit project report and documents to bank.",
    approvalProcess: "Bank appraises and sanctions. Ministry provides interest subvention.",
    fundReleaseProcess: "Disbursed as per project milestones.",
    processingTimeline: "30-90 days",
    consultantChecklist: "Detailed DPR, land documents, quotations, clear project viability.",
    customerBenefits: "Long-term loan, interest subvention, boost to agri-infrastructure.",
    commonMistakes: "Incomplete land documents, unrealistic project cost.",
    commonRejectionReasons: "Non-viable project, weak cash flow projections.",
    consultantNotes: "Ideal for cold storage, silos, processing units, and primary processing centers.",
    customerPitch: "Agriculture Infrastructure Fund आपको कृषि infrastructure जैसे cold storage या processing unit के लिए सस्ता loan देता है।",
    faq: [
      { q: "AIF से क्या-क्या बन सकता है?", a: "Cold storage, warehousing, silos, processing units, and primary processing centers." },
      { q: "Interest subvention कितना है?", a: "2% per annum, reducing effective interest rate." }
    ],
    relatedSchemes: ["pmfme", "midh"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "pmfme",
    schemeName: "PM Formalisation of Micro Food Processing Enterprises",
    alternativeNames: ["PMFME"],
    launchYear: 2020,
    ministry: "Ministry of Food Processing Industries",
    department: "MoFPI",
    officialPortal: "www.pmfme.mofpi.gov.in",
    officialGuideline: "https://www.pmfme.mofpi.gov.in/",
    objective: "To formalize and support micro food processing enterprises with credit, technology, and marketing.",
    overview: "PMFME provides seed capital, working capital, and equipment subsidy to micro food processing units. It aims to upgrade 2 lakh units.",
    category: "Food Processing",
    sector: "Food Processing, Agro-Processing",
    businessTypes: ["Food Processing", "Micro Enterprise", "Agri-Processing"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "FPO"],
    whoCanApply: "Micro food processing enterprises, FPOs, co-operatives, and individual entrepreneurs.",
    whoCannotApply: "Large food processing units, non-food businesses.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any, but existing units preferred.",
    turnoverRequirement: "Less than ₹5 crore",
    investmentRequirement: "Up to ₹50 lakh",
    fundingType: "Seed Capital + Working Capital + Subsidy",
    loanComponent: "Loan from bank",
    grantComponent: "Seed capital (₹10,000 per member for FPOs)",
    subsidyComponent: "Equipment subsidy (up to 35%)",
    maximumFunding: 5000000,
    ownContribution: "5-10%",
    marginMoney: null,
    interestInformation: "Bank rate + interest subvention",
    moratorium: "6 months",
    repaymentTenure: "3-5 years",
    collateralRequirement: "No collateral up to ₹10 lakh",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Quotations", "GST", "FSSAI License"],
    optionalDocuments: ["Technical Report", "Training Certificate"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "FSSAI", "MSME Registration"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through district Nodal Officer or online portal. Submit project and documents.",
    approvalProcess: "District committee approves, bank sanctions loan.",
    fundReleaseProcess: "Seed capital released, loan disbursed, subsidy after installation.",
    processingTimeline: "45-90 days",
    consultantChecklist: "FSSAI license mandatory, detailed project report, quotations for machinery.",
    customerBenefits: "Seed capital, equipment subsidy, working capital support.",
    commonMistakes: "Not having FSSAI, incomplete project report, overestimation.",
    commonRejectionReasons: "Incomplete documents, non-viable project, lack of FSSAI.",
    consultantNotes: "PMFME is a boon for small food processors. Focus on common facility centers for better impact.",
    customerPitch: "PMFME आपको food processing business के लिए seed capital, subsidy और working capital देता है।",
    faq: [
      { q: "PMFME में कितनी subsidy मिलती है?", a: "Equipment subsidy up to 35% of project cost." },
      { q: "क्या मैं existing business के लिए apply कर सकता हूँ?", a: "Yes, existing micro food processing units are eligible." }
    ],
    relatedSchemes: ["agriculture_infrastructure_fund", "midh"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "midh",
    schemeName: "Mission for Integrated Development of Horticulture",
    alternativeNames: ["MIDH"],
    launchYear: 2014,
    ministry: "Ministry of Agriculture and Farmers' Welfare",
    department: "Department of Agriculture",
    officialPortal: "www.midh.gov.in",
    officialGuideline: "https://www.midh.gov.in/",
    objective: "To promote holistic growth of horticulture sector through area-based, regionally differentiated strategies.",
    overview: "MIDH covers fruits, vegetables, root and tuber crops, mushrooms, spices, flowers, aromatic plants, and plantation crops. It provides subsidy for nursery, plantation, and post-harvest infrastructure.",
    category: "Agriculture",
    sector: "Horticulture, Agriculture, Floriculture",
    businessTypes: ["Horticulture", "Floriculture", "Fruit/Veg Grower", "Spice Grower"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "FPO", "Cooperative"],
    whoCanApply: "Farmers, FPOs, co-operatives, entrepreneurs, and companies engaged in horticulture.",
    whoCannotApply: "Non-horticulture businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Subsidy",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: "40-60% of project cost (varies by component and region)",
    maximumFunding: null,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["KYC", "Land Documents", "Project Report", "Bank Account"],
    optionalDocuments: ["Technical Report", "Quotations"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["GST (if applicable)"],
    applicationMode: "Offline",
    applicationProcess: "Apply through State Horticulture Mission or District Horticulture Officer.",
    approvalProcess: "State level committee approves projects based on feasibility.",
    fundReleaseProcess: "Subsidy released in stages after verification.",
    processingTimeline: "30-90 days",
    consultantChecklist: "Ensure land ownership, prepare project report, check regional priorities.",
    customerBenefits: "High subsidy for horticulture projects, technical support.",
    commonMistakes: "Incomplete land documents, not following recommended practices.",
    commonRejectionReasons: "Land dispute, non-viable project, incomplete application.",
    consultantNotes: "MIDH is a comprehensive horticulture scheme. Focus on high-value crops.",
    customerPitch: "MIDH आपको horticulture projects के लिए 40-60% subsidy देता है।",
    faq: [
      { q: "MIDH में कौन-कौन सी crops cover हैं?", a: "Fruits, vegetables, spices, flowers, aromatic plants, and plantation crops." },
      { q: "कितनी subsidy मिलती है?", a: "40-60% depending on the component and region." }
    ],
    relatedSchemes: ["agriculture_infrastructure_fund", "pmfme"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "national_livestock_mission",
    schemeName: "National Livestock Mission",
    alternativeNames: ["NLM"],
    launchYear: 2014,
    ministry: "Ministry of Fisheries, Animal Husbandry and Dairying",
    department: "Department of Animal Husbandry and Dairying",
    officialPortal: "www.dahd.nic.in",
    officialGuideline: "https://dahd.nic.in/schemes/national-livestock-mission",
    objective: "To ensure sustainable development of livestock sector with focus on productivity, entrepreneurship, and employment.",
    overview: "NLM promotes livestock entrepreneurship through support for dairy, poultry, goat, sheep, and piggery projects. It provides capital subsidy for infrastructure and animal purchase.",
    category: "Agriculture",
    sector: "Livestock, Dairy, Poultry, Goat, Sheep, Piggery",
    businessTypes: ["Livestock Farming", "Dairy", "Poultry", "Goat/Sheep Farming", "Piggery"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "FPO", "Cooperative"],
    whoCanApply: "Individuals, FPOs, co-operatives, and companies with land and capacity for livestock farming.",
    whoCannotApply: "Non-livestock businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Capital Subsidy",
    loanComponent: "Balance amount from bank",
    grantComponent: null,
    subsidyComponent: "40-50% of project cost (varies by category and region)",
    maximumFunding: null,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate as applicable",
    moratorium: "6-12 months",
    repaymentTenure: "3-7 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Land Documents", "Project Report", "Quotations", "Bank Account"],
    optionalDocuments: ["Veterinary Certificate", "Technical Report"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "License from Animal Husbandry Department"],
    applicationMode: "Offline",
    applicationProcess: "Apply through State Animal Husbandry Department. Submit project proposal.",
    approvalProcess: "State-level committee approves, bank sanctions loan.",
    fundReleaseProcess: "Subsidy released after verification and loan disbursement.",
    processingTimeline: "45-90 days",
    consultantChecklist: "Land ownership, animal housing design, biosecurity plan.",
    customerBenefits: "Subsidy for livestock infrastructure, improved breed availability.",
    commonMistakes: "Inadequate housing design, lack of veterinary plan.",
    commonRejectionReasons: "Non-viable project, incomplete documents, land issues.",
    consultantNotes: "NLM is ideal for commercial dairy and poultry. Ensure proper animal welfare practices.",
    customerPitch: "National Livestock Mission आपको dairy, poultry, goat farming के लिए 40-50% subsidy देता है।",
    faq: [
      { q: "NLM में किस-किस animal को cover किया गया है?", a: "Dairy cattle, buffalo, poultry, goat, sheep, piggery, and small ruminants." },
      { q: "कितनी subsidy मिलती है?", a: "40-50% of project cost (depending on category and region)." }
    ],
    relatedSchemes: ["didf", "agriculture_infrastructure_fund"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "didf",
    schemeName: "Dairy Infrastructure Development Fund",
    alternativeNames: ["DIDF"],
    launchYear: 2018,
    ministry: "Ministry of Fisheries, Animal Husbandry and Dairying",
    department: "Department of Animal Husbandry and Dairying",
    officialPortal: "www.dahd.nic.in",
    officialGuideline: "https://dahd.nic.in/schemes/dairy-infrastructure-development-fund",
    objective: "To strengthen dairy infrastructure including milk processing, chilling plants, and value addition.",
    overview: "DIDF provides loans at concessional rates to dairy co-operatives and private entities for setting up processing plants, chilling centers, and value addition facilities.",
    category: "Agriculture",
    sector: "Dairy, Milk Processing",
    businessTypes: ["Dairy Processing", "Chilling Center", "Milk Processing Plant", "Dairy Value Addition"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Cooperative", "FPO"],
    whoCanApply: "Dairy co-operatives, private companies, FPOs, and partnerships with proven dairy experience.",
    whoCannotApply: "Non-dairy businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Minimum 2 years in dairy business",
    turnoverRequirement: null,
    investmentRequirement: "Minimum ₹50 lakh",
    fundingType: "Term Loan + Interest Subvention",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "Interest subvention up to 2%",
    maximumFunding: null,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate - 2% interest subvention",
    moratorium: "Up to 2 years",
    repaymentTenure: "Up to 10 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Land Documents", "Bank Statements", "GST"],
    optionalDocuments: ["Technical Feasibility Report", "Quotations"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "FSSAI License", "Dairy License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through NABARD or bank. Submit detailed project report.",
    approvalProcess: "NABARD/bank appraises, and DAHD recommends subvention.",
    fundReleaseProcess: "Loan disbursed in stages, subvention credited to account.",
    processingTimeline: "60-90 days",
    consultantChecklist: "Detailed DPR, land documents, clear dairy experience.",
    customerBenefits: "Long-term loan, interest subvention, boost to dairy infrastructure.",
    commonMistakes: "Incomplete project report, land title issues.",
    commonRejectionReasons: "Weak business plan, non-viable project, lack of dairy experience.",
    consultantNotes: "DIDF is ideal for large dairy projects. Ensure strong backward integration with farmers.",
    customerPitch: "Dairy Infrastructure Development Fund आपको milk processing plant या chilling center के लिए cheap loan देता है।",
    faq: [
      { q: "DIDF के लिए कितनी interest subvention है?", a: "2% per annum subvention, reducing effective interest rate." },
      { q: "क्या मैं existing dairy plant upgrade के लिए apply कर सकता हूँ?", a: "Yes, up-gradation and modernization are eligible." }
    ],
    relatedSchemes: ["national_livestock_mission"],
    lastUpdated: "2025-01-15"
  },
  // ======================== WOMEN / SC/ST / MINORITY SCHEMES ========================
  {
    id: "stand_up_india",
    schemeName: "Stand-Up India Scheme",
    alternativeNames: ["Stand-Up India"],
    launchYear: 2016,
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    officialPortal: "www.standupmitra.in",
    officialGuideline: "https://www.standupmitra.in/",
    objective: "To promote entrepreneurship among SC/ST and women by providing loans for greenfield enterprises.",
    overview: "Stand-Up India provides bank loans between ₹10 lakh to ₹1 crore for setting up new enterprises by SC/ST or women entrepreneurs. At least one woman and one SC/ST borrower per bank branch.",
    category: "MSME",
    sector: "All sectors (except prohibited)",
    businessTypes: ["Greenfield Enterprise", "Manufacturing", "Service", "Trade"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited"],
    whoCanApply: "SC/ST entrepreneurs and women (non-SC/ST) with a viable business idea.",
    whoCannotApply: "Existing businesses, defaulters, non-SC/ST men.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Greenfield (new) enterprise only",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Term Loan + Working Capital",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: 10000000,
    ownContribution: "10% margin money",
    marginMoney: "10% of project cost",
    interestInformation: "Bank rate as applicable (no special subsidy)",
    moratorium: "Up to 18 months",
    repaymentTenure: "5-7 years",
    collateralRequirement: "No collateral (CGTMSE cover)",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "SC/ST/Caste Certificate", "Women Certificate", "Bank Account"],
    optionalDocuments: ["Training Certificate", "Experience Letter"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["GST", "MSME Registration"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply to any bank branch. Submit project report and documents.",
    approvalProcess: "Bank appraises and sanctions based on viability.",
    fundReleaseProcess: "Loan disbursed in full or in stages.",
    processingTimeline: "30-45 days",
    consultantChecklist: "Ensure caste/category certificates are valid, project is greenfield.",
    customerBenefits: "Collateral-free loan, dedicated for women/SC/ST, working capital included.",
    commonMistakes: "Not providing valid category certificate, non-greenfield project.",
    commonRejectionReasons: "Invalid category, non-viable project, incomplete documents.",
    consultantNotes: "Stand-Up India is a game-changer for women and SC/ST entrepreneurs. Focus on viable projects.",
    customerPitch: "Stand-Up India आपको SC/ST और महिला entrepreneurs के लिए ₹1 करोड़ तक का collateral-free loan देता है।",
    faq: [
      { q: "क्या मैं Stand-Up India loan दोबारा ले सकता हूँ?", a: "No, it's a one-time loan for greenfield enterprises." },
      { q: "क्या मुझे category certificate चाहिए?", a: "Yes, SC/ST certificate or women certificate (for non-SC/ST women)." }
    ],
    relatedSchemes: ["cgtmse", "mudra_yojana"],
    lastUpdated: "2025-01-15"
  },
  // ======================== EXPORT SCHEMES ========================
  {
    id: "epcg",
    schemeName: "Export Promotion Capital Goods Scheme",
    alternativeNames: ["EPCG"],
    launchYear: 2019,
    ministry: "Ministry of Commerce and Industry",
    department: "DGFT",
    officialPortal: "www.dgft.gov.in",
    officialGuideline: "https://dgft.gov.in/CP/?opt=epcg",
    objective: "To enable import of capital goods for pre-production, production, and post-production at zero duty, subject to export obligation.",
    overview: "EPCG allows zero customs duty import of capital goods by exporters, with a commitment to export 6 times the duty saved value over a period.",
    category: "Export",
    sector: "All export-oriented sectors",
    businessTypes: ["Exporter", "Manufacturing", "Service Exporter", "Trading"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "Any entity with a valid IEC and export track record, or commitment to export.",
    whoCannotApply: "Non-exporters, defaulters, entities without IEC.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any, but export track record preferred.",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Duty Exemption",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: null,
    ownContribution: null,
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: "Bank guarantee for some cases",
    processingFees: "As per DGFT",
    requiredDocuments: ["IEC", "Bill of Entry", "Export Obligation Bond", "Project Report"],
    optionalDocuments: ["Technology Collaboration Agreement", "R&D Certificate"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["IEC", "GST (for refund)"],
    applicationMode: "Online",
    applicationProcess: "Apply through DGFT online portal. Submit IE code and export commitment.",
    approvalProcess: "DGFT grants authorization based on export obligation.",
    fundReleaseProcess: "N/A (duty exemption at customs)",
    processingTimeline: "15-30 days",
    consultantChecklist: "Ensure IEC is active, export plan is realistic, and obligation is manageable.",
    customerBenefits: "Zero duty on capital goods, improved competitiveness.",
    commonMistakes: "Underestimating export obligation, not tracking compliance.",
    commonRejectionReasons: "Invalid IEC, unrealistic export commitment.",
    consultantNotes: "EPCG is best for manufacturing exporters. Calculate duty saved vs. export obligation carefully.",
    customerPitch: "EPCG आपको manufacturing machinery import पर zero duty का लाभ देता है, बस export commitment के साथ।",
    faq: [
      { q: "EPCG में export obligation क्या है?", a: "6 times the duty saved value over 6 years (or 8 years for certain sectors)." },
      { q: "क्या मैं EPCG को trading business के लिए use कर सकता हूँ?", a: "Yes, but trading exporters have different obligation norms." }
    ],
    relatedSchemes: ["market_access_initiative"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "market_access_initiative",
    schemeName: "Market Access Initiative",
    alternativeNames: ["MAI"],
    launchYear: 2017,
    ministry: "Ministry of Commerce and Industry",
    department: "DGFT",
    officialPortal: "www.commerce.gov.in",
    officialGuideline: "https://commerce.gov.in/schemes/market-access-initiative/",
    objective: "To promote Indian exports through financial support for market research, participation in trade fairs, and brand building.",
    overview: "MAI provides financial assistance to exporters, trade bodies, and industry associations for export promotion activities including buyer-seller meets, trade fairs, and market studies.",
    category: "Export",
    sector: "All export sectors",
    businessTypes: ["Exporter", "Trade Body", "Industry Association"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship", "Association"],
    whoCanApply: "Exporters with IEC, trade bodies, chambers of commerce, and industry associations.",
    whoCannotApply: "Non-exporters, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any, but IEC required.",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Grant",
    loanComponent: null,
    grantComponent: "Financial assistance up to 100% of eligible expenses (capped)",
    subsidyComponent: null,
    maximumFunding: null,
    ownContribution: null,
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["IEC", "Trade Fair Registration", "Project Report", "KYC"],
    optionalDocuments: ["Brand Registration", "Marketing Material"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["IEC"],
    applicationMode: "Online",
    applicationProcess: "Apply through DGFT portal. Submit proposal for export promotion activity.",
    approvalProcess: "DGFT approves based on merit and budget availability.",
    fundReleaseProcess: "Grant released after activity completion.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Identify target markets, prepare a clear marketing plan.",
    customerBenefits: "Financial support for export promotion, enhanced visibility.",
    commonMistakes: "Incomplete project proposal, no post-event report.",
    commonRejectionReasons: "Budget constraints, poor proposal.",
    consultantNotes: "MAI is ideal for SMEs looking to enter new international markets.",
    customerPitch: "Market Access Initiative आपको international trade fairs और buyer meets के लिए financial support देता है।",
    faq: [
      { q: "MAI से क्या-क्या cover होता है?", a: "Trade fair participation, buyer-seller meets, market studies, brand promotion." },
      { q: "कितनी financial support मिलती है?", a: "Up to 100% of eligible expenses (capped per activity)." }
    ],
    relatedSchemes: ["epcg"],
    lastUpdated: "2025-01-15"
  },
  // ======================== TECHNOLOGY & INNOVATION ========================
  {
    id: "digital_msme",
    schemeName: "Digital MSME Scheme",
    alternativeNames: ["MSME Digital"],
    launchYear: 2020,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/digital-msme",
    objective: "To promote digitalization among MSMEs through cloud computing, automation, and digital tools.",
    overview: "Digital MSME provides financial support for MSMEs to adopt digital technologies including ERP, CRM, accounting software, and e-commerce platforms.",
    category: "Technology",
    sector: "All MSME sectors",
    businessTypes: ["Manufacturing", "Service", "Trade", "Retail", "E-commerce"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "LLP"],
    whoCanApply: "MSMEs with Udyam Registration, willing to adopt digital tools.",
    whoCannotApply: "Non-MSMEs, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Grant + Subsidy",
    loanComponent: null,
    grantComponent: "Up to 50% of project cost",
    subsidyComponent: "Other components",
    maximumFunding: 500000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Project Proposal", "Quotations", "KYC"],
    optionalDocuments: ["Training Certificate", "Existing Tech Details"],
    dprRequired: false,
    quotationRequired: true,
    licensesRequired: ["Udyam Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply through MSME portal. Submit proposal for digital adoption.",
    approvalProcess: "MSME Ministry approves based on viability and budget.",
    fundReleaseProcess: "Grant released after implementation and verification.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Identify digital tools needed, prepare implementation plan.",
    customerBenefits: "Cost-effective digital adoption, improved efficiency.",
    commonMistakes: "Unclear tech adoption plan, incomplete quotations.",
    commonRejectionReasons: "Budget constraints, poor proposal.",
    consultantNotes: "Digital MSME is a stepping stone for Industry 4.0 adoption.",
    customerPitch: "Digital MSME आपको ERP, CRM और e-commerce के लिए 50% तक का grant देता है।",
    faq: [
      { q: "Digital MSME में कौन-कौन सी technologies cover हैं?", a: "ERP, CRM, accounting software, inventory management, e-commerce platforms." },
      { q: "कितना grant मिल सकता है?", a: "Up to 50% of project cost, max ₹5 lakh." }
    ],
    relatedSchemes: ["incubation_scheme"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "lean_manufacturing",
    schemeName: "Lean Manufacturing Competitiveness Scheme",
    alternativeNames: ["Lean Manufacturing"],
    launchYear: 2014,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/lean-manufacturing",
    objective: "To help MSMEs reduce waste, improve efficiency, and enhance competitiveness through lean manufacturing techniques.",
    overview: "Lean Manufacturing scheme provides financial assistance for MSMEs to adopt lean tools like 5S, Kaizen, Just-in-Time, and Value Stream Mapping.",
    category: "Manufacturing",
    sector: "All manufacturing sectors",
    businessTypes: ["Manufacturing", "Industrial", "Production"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "Manufacturing MSMEs with Udyam registration.",
    whoCannotApply: "Service sector, non-MSMEs, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1 year",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Grant",
    loanComponent: null,
    grantComponent: "Up to 80% of consultancy cost",
    subsidyComponent: null,
    maximumFunding: 1000000,
    ownContribution: "20% of consultancy cost",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Lean Implementation Plan", "KYC", "Bank Account"],
    optionalDocuments: ["Existing Production Data", "Quality Certificates"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply through MSME portal. Select a lean consultant and submit proposal.",
    approvalProcess: "MSME Ministry approves based on viability.",
    fundReleaseProcess: "Grant released after implementation and verification.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Choose a certified lean consultant, define clear KPIs.",
    customerBenefits: "Cost reduction, productivity improvement, waste minimization.",
    commonMistakes: "Unclear goals, not tracking benefits.",
    commonRejectionReasons: "Budget constraints, poor proposal.",
    consultantNotes: "Lean Manufacturing is a proven methodology for MSME cost reduction.",
    customerPitch: "Lean Manufacturing scheme आपको waste reduce करके 80% consultancy cost grant देता है।",
    faq: [
      { q: "Lean Manufacturing में कौन-कौन सी techniques cover हैं?", a: "5S, Kaizen, JIT, VSM, TPM, and other lean tools." },
      { q: "कितना grant मिलता है?", a: "Up to 80% of consultancy cost, max ₹10 lakh." }
    ],
    relatedSchemes: ["digital_msme"],
    lastUpdated: "2025-01-15"
  },
  // ======================== SOLAR & GREEN ENERGY ========================
  {
    id: "solar_subsidy",
    schemeName: "Grid-Connected Rooftop Solar Subsidy Scheme",
    alternativeNames: ["Solar Rooftop Subsidy", "Surya Gujarat", "PM Surya Ghar"],
    launchYear: 2022,
    ministry: "Ministry of New and Renewable Energy",
    department: "MNRE",
    officialPortal: "www.mnre.gov.in",
    officialGuideline: "https://mnre.gov.in/solar-rooftop/",
    objective: "To promote rooftop solar installations on residential and commercial buildings with capital subsidy.",
    overview: "MNRE provides subsidy for rooftop solar PV systems up to 10 kW capacity. Central financial assistance is provided for residential and institutional buildings.",
    category: "Green Energy",
    sector: "Energy, Solar, Power",
    businessTypes: ["Solar Installation", "Residential", "Commercial", "Industrial"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "Society", "Resident Association"],
    whoCanApply: "Any individual, institution, MSME, or residential society with a building.",
    whoCannotApply: "Non-building premises, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Capital Subsidy",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: "40% (up to 3 kW), 20% (3-10 kW) of benchmark cost",
    maximumFunding: null,
    ownContribution: "Balance cost",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Building Ownership Proof", "Electricity Bill", "KYC", "Technical Proposal"],
    optionalDocuments: ["Load Sanction Letter", "Structural Stability Certificate"],
    dprRequired: false,
    quotationRequired: true,
    licensesRequired: ["Electrical Contractor License", "GST (if applicable)"],
    applicationMode: "Online",
    applicationProcess: "Apply through State Discom portal. Get technical feasibility approved, install system, and claim subsidy.",
    approvalProcess: "Discom approves technical feasibility and sanctions net metering.",
    fundReleaseProcess: "Subsidy released directly to vendor or beneficiary after commissioning.",
    processingTimeline: "30-90 days",
    consultantChecklist: "Check roof capacity, solar potential, and structural soundness.",
    customerBenefits: "Capital subsidy, lower electricity bills, net metering benefits.",
    commonMistakes: "Not checking structural load capacity, under-sizing system.",
    commonRejectionReasons: "Technical infeasibility, incomplete application.",
    consultantNotes: "Solar rooftop is a no-brainer for MSMEs with high electricity consumption.",
    customerPitch: "Solar Rooftop Scheme आपको 40% तक subsidy के साथ solar installation का opportunity देता है।",
    faq: [
      { q: "Rooftop solar के लिए कितनी subsidy मिलती है?", a: "40% up to 3 kW, 20% up to 10 kW." },
      { q: "क्या मैं commercial building पर solar लगा सकता हूँ?", a: "Yes, commercial, industrial, and institutional buildings are eligible." }
    ],
    relatedSchemes: [],
    lastUpdated: "2025-01-15"
  },
  // ======================== TEXTILE SCHEMES ========================
  {
    id: "textile_technology_upgradation",
    schemeName: "Technology Upgradation Fund Scheme for Textiles",
    alternativeNames: ["TUFS"],
    launchYear: 2014,
    ministry: "Ministry of Textiles",
    department: "Textiles Ministry",
    officialPortal: "www.textiles.gov.in",
    officialGuideline: "https://textiles.gov.in/tufs",
    objective: "To encourage modernization and technology upgradation in the textile and apparel industry.",
    overview: "TUFS provides interest subvention and capital subsidy for textile units investing in modern machinery and technology.",
    category: "Textile",
    sector: "Textile, Apparel, Garments, Handloom, Powerloom",
    businessTypes: ["Textile Manufacturer", "Garment Manufacturer", "Handloom", "Powerloom", "Processing"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "Textile units registered under any entity type, with a project for technology upgradation.",
    whoCannotApply: "Non-textile businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: "Minimum ₹50 lakh",
    fundingType: "Interest Subvention + Capital Subsidy",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "10-15% capital subsidy (for certain machines)",
    maximumFunding: null,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate - 5% subvention (for eligible loans)",
    moratorium: "Up to 12 months",
    repaymentTenure: "5-7 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Quotations", "Bank Statements", "GST"],
    optionalDocuments: ["Technical Report", "Power Connection"],
    dprRequired: true,
    quotationRequired: true,
    licensesRequired: ["GST", "MSME Registration", "Textiles License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through designated bank. Submit project report and documents.",
    approvalProcess: "Bank appraises, and Textiles Ministry approves subvention.",
    fundReleaseProcess: "Loan disbursed, subvention credited to account.",
    processingTimeline: "45-90 days",
    consultantChecklist: "Prepare detailed project report, choose eligible machinery.",
    customerBenefits: "Interest subvention, capital subsidy, modernized operations.",
    commonMistakes: "Not choosing eligible machinery, incomplete documentation.",
    commonRejectionReasons: "Non-eligible machinery, weak financials.",
    consultantNotes: "TUFS is a strategic scheme for textile sector modernization.",
    customerPitch: "TUFS आपको textile machinery upgradation के लिए 5% interest subvention और capital subsidy देता है।",
    faq: [
      { q: "TUFS में कौन-कौन से machines eligible हैं?", a: "List of eligible machines is published by Textiles Ministry annually." },
      { q: "कितनी capital subsidy मिलती है?", a: "10-15% on eligible machinery (specific list)." }
    ],
    relatedSchemes: ["cgtmse"],
    lastUpdated: "2025-01-15"
  },
  // ======================== HEALTHCARE & TOURISM ========================
  {
    id: "healthcare_msme",
    schemeName: "Healthcare MSME Scheme",
    alternativeNames: ["Medical Devices", "Healthcare Funding"],
    launchYear: 2021,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/healthcare-msme",
    objective: "To support MSMEs in the healthcare sector including medical device manufacturing and diagnostics.",
    overview: "Healthcare MSME scheme provides credit support, technology upgradation, and quality certification assistance to healthcare MSMEs.",
    category: "Healthcare",
    sector: "Healthcare, Medical Devices, Diagnostics, Pharma",
    businessTypes: ["Medical Device Manufacturing", "Diagnostics", "Pharma Manufacturing", "Healthcare Services"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "MSMEs in healthcare sector with Udyam registration.",
    whoCannotApply: "Non-healthcare businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1 year",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Working Capital + Term Loan",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "Interest subvention (2%)",
    maximumFunding: 50000000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate - 2% subvention",
    moratorium: "6-12 months",
    repaymentTenure: "3-7 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Licenses", "Bank Statements"],
    optionalDocuments: ["Quality Certificates", "Clinical Reports"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["GST", "Drug License", "ISO (if applicable)"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through bank or MSME portal.",
    approvalProcess: "Bank appraises and sanctions.",
    fundReleaseProcess: "Disbursed as per project milestones.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Ensure all mandatory licenses are in place.",
    customerBenefits: "Interest subvention, working capital support, technology upgradation.",
    commonMistakes: "Missing licenses, incomplete documentation.",
    commonRejectionReasons: "Non-compliance with regulatory norms.",
    consultantNotes: "Healthcare MSMEs should focus on regulatory compliance and quality certifications.",
    customerPitch: "Healthcare MSME scheme आपको medical device manufacturing और diagnostics के लिए cheap loan provides करता है।",
    faq: [
      { q: "Healthcare MSME में क्या-क्या cover है?", a: "Medical devices, diagnostics, pharma, and healthcare services." },
      { q: "कितनी interest subvention मिलती है?", a: "2% per annum subvention." }
    ],
    relatedSchemes: ["mudra_yojana", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "tourism_msme",
    schemeName: "Tourism MSME Support Scheme",
    alternativeNames: ["Tourism Funding", "Travel MSME"],
    launchYear: 2020,
    ministry: "Ministry of Tourism",
    department: "Tourism Ministry",
    officialPortal: "www.tourism.gov.in",
    officialGuideline: "https://tourism.gov.in/schemes",
    objective: "To support MSMEs in the tourism sector including hotels, tour operators, and travel agencies.",
    overview: "Tourism MSME scheme provides working capital loans, interest subvention, and marketing support to tourism sector MSMEs.",
    category: "Tourism",
    sector: "Tourism, Hospitality, Travel, Hotel, Resort",
    businessTypes: ["Hotel", "Resort", "Tour Operator", "Travel Agency", "Homestay"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "MSMEs in tourism sector with Udyam registration.",
    whoCannotApply: "Non-tourism businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1 year",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Working Capital + Term Loan",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: "Interest subvention (2%)",
    maximumFunding: 50000000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate - 2% subvention",
    moratorium: "6-12 months",
    repaymentTenure: "3-7 years",
    collateralRequirement: "As per bank",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Project Report", "Licenses", "Bank Statements"],
    optionalDocuments: ["Tourism Department Registration", "Marketing Plan"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["GST", "Tourism License", "Fire License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through bank or Tourism Ministry portal.",
    approvalProcess: "Bank appraises and sanctions.",
    fundReleaseProcess: "Disbursed as per project milestones.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Ensure all hospitality licenses are in place.",
    customerBenefits: "Interest subvention, working capital support, marketing assistance.",
    commonMistakes: "Incomplete licenses, poor marketing plan.",
    commonRejectionReasons: "Non-compliance with tourism regulations.",
    consultantNotes: "Tourism sector MSMEs should leverage digital marketing.",
    customerPitch: "Tourism MSME scheme आपको hotels, resorts, और travel agencies के लिए cheap loan and marketing support देता है।",
    faq: [
      { q: "Tourism MSME में कौन-कौन apply कर सकता है?", a: "Hotels, resorts, tour operators, travel agencies, homestays." },
      { q: "कितनी interest subvention मिलती है?", a: "2% per annum subvention." }
    ],
    relatedSchemes: ["mudra_yojana", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  // ======================== RETAIL & SERVICE ========================
  {
    id: "service_msme",
    schemeName: "Service Sector MSME Scheme",
    alternativeNames: ["Service MSME", "Service Business Loan"],
    launchYear: 2019,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/service-sector",
    objective: "To support MSMEs in the service sector with working capital and term loans at concessional rates.",
    overview: "Service sector MSMEs (IT, consulting, logistics, etc.) get access to credit at lower interest rates with government guarantee.",
    category: "Service",
    sector: "IT, Consulting, Logistics, Education, Healthcare, Beauty, Salon, etc.",
    businessTypes: ["IT Services", "Consulting", "Logistics", "Education", "Healthcare", "Beauty", "Salon"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "MSMEs in service sector with Udyam registration.",
    whoCannotApply: "Non-service businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1 year",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Working Capital + Term Loan",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: 50000000,
    ownContribution: "10-20%",
    marginMoney: null,
    interestInformation: "Bank rate + government guarantee fee",
    moratorium: "6 months",
    repaymentTenure: "3-5 years",
    collateralRequirement: "No collateral for up to ₹25 lakh (CGTMSE)",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "Business Plan", "Bank Statements", "GST"],
    optionalDocuments: ["Professional Certificates", "Client List"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["GST", "Professional License (if applicable)"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through bank. Submit business plan and financials.",
    approvalProcess: "Bank appraises and sanctions.",
    fundReleaseProcess: "Disbursed as per need.",
    processingTimeline: "15-30 days",
    consultantChecklist: "Maintain clean bank statements, prepare business plan.",
    customerBenefits: "Collateral-free credit, quick processing, flexible terms.",
    commonMistakes: "Incomplete GST, poor business plan.",
    commonRejectionReasons: "Low CIBIL, incomplete documentation.",
    consultantNotes: "Service sector MSMEs should focus on cash flow management.",
    customerPitch: "Service MSME scheme आपको IT, consulting, logistics और education sector के लिए easy loan provides करता है।",
    faq: [
      { q: "Service MSME में कौन-कौन सी businesses cover हैं?", a: "IT, consulting, logistics, education, healthcare, beauty, and other services." },
      { q: "कितनी funding मिल सकती है?", a: "Up to ₹5 crore, with CGTMSE guarantee up to ₹25 lakh." }
    ],
    relatedSchemes: ["mudra_yojana", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  // ======================== RETAIL (MSME RETAIL) ========================
  {
    id: "retail_msme",
    schemeName: "Retail MSME Scheme",
    alternativeNames: ["Retail Business Loan", "Shop Loan"],
    launchYear: 2021,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/retail-msme",
    objective: "To support retail MSMEs including shops, supermarkets, and e-commerce sellers with working capital.",
    overview: "Retail sector MSMEs get access to collateral-free working capital loans for inventory, expansion, and digitization.",
    category: "Retail",
    sector: "Retail, E-commerce, Wholesale, Distribution",
    businessTypes: ["Retail Shop", "Supermarket", "E-commerce Seller", "Wholesale Store", "Distribution"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "LLP"],
    whoCanApply: "Retail MSMEs with Udyam registration.",
    whoCannotApply: "Non-retail businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 6 months",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Working Capital",
    loanComponent: "Loan from bank",
    grantComponent: null,
    subsidyComponent: null,
    maximumFunding: 5000000,
    ownContribution: null,
    marginMoney: null,
    interestInformation: "Bank rate + guarantee fee",
    moratorium: "3-6 months",
    repaymentTenure: "3-5 years",
    collateralRequirement: "No collateral (CGTMSE cover)",
    processingFees: "As per bank",
    requiredDocuments: ["KYC", "GST Registration", "Bank Statements", "Sales Proof"],
    optionalDocuments: ["Shop Rental Agreement", "Inventory Details"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["GST", "Shop License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through bank. Submit sales data and inventory details.",
    approvalProcess: "Bank appraises based on sales and cash flow.",
    fundReleaseProcess: "Disbursed as working capital.",
    processingTimeline: "7-15 days",
    consultantChecklist: "Maintain digital sales records, GST compliance.",
    customerBenefits: "Collateral-free working capital, quick processing.",
    commonMistakes: "Incomplete sales records, poor GST compliance.",
    commonRejectionReasons: "Low sales turnover, incomplete documentation.",
    consultantNotes: "Retail MSMEs should leverage UPI and digital payments for better records.",
    customerPitch: "Retail MSME scheme आपको shop, supermarket या e-commerce business के लिए collateral-free working capital देता है।",
    faq: [
      { q: "Retail MSME में कौन apply कर सकता है?", a: "Retail shops, supermarkets, e-commerce sellers, wholesale distributors." },
      { q: "कितना loan मिल सकता है?", a: "Up to ₹50 lakh (collateral-free)." }
    ],
    relatedSchemes: ["mudra_yojana", "cgtmse"],
    lastUpdated: "2025-01-15"
  },
  // ======================== ADDITIONAL SCHEMES (CLUSTER, ZED, DESIGN, etc.) ========================
  {
    id: "msme_cluster_development",
    schemeName: "MSME Cluster Development Programme",
    alternativeNames: ["Cluster Development", "MSE-CDP"],
    launchYear: 2017,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/cluster-development-programme",
    objective: "To promote the growth of MSME clusters by providing common facilities, infrastructure, and marketing support.",
    overview: "Cluster development programme identifies and supports clusters of MSMEs in specific sectors to enhance competitiveness through common facilities, training, and marketing.",
    category: "MSME",
    sector: "All MSME clusters",
    businessTypes: ["Cluster-based MSME", "Manufacturing", "Service", "Handicraft"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "LLP", "Cooperative"],
    whoCanApply: "MSMEs within identified clusters (association/spcs can apply).",
    whoCannotApply: "Non-cluster businesses, individual MSMEs outside clusters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Grant",
    loanComponent: null,
    grantComponent: "Up to 80% of project cost (common facilities)",
    subsidyComponent: null,
    maximumFunding: null,
    ownContribution: "20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Cluster Identity", "Project Proposal", "KYC", "Association Registration"],
    optionalDocuments: ["Technical Report", "Feasibility Study"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration", "GST"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through MSME Ministry or State MSME department.",
    approvalProcess: "State/National committee approves based on cluster potential.",
    fundReleaseProcess: "Grant released in stages after verification.",
    processingTimeline: "60-120 days",
    consultantChecklist: "Ensure cluster identification, prepare feasibility report.",
    customerBenefits: "Common facilities, reduced costs, shared infrastructure.",
    commonMistakes: "Incomplete cluster mapping, unrealistic proposals.",
    commonRejectionReasons: "Cluster not recognized, budget constraints.",
    consultantNotes: "Cluster development is a strategic intervention for MSME competitiveness.",
    customerPitch: "MSME Cluster Development आपको common facilities और infrastructure के लिए 80% grant देता है।",
    faq: [
      { q: "Cluster Development में क्या-क्या facilities cover होती हैं?", a: "Common testing labs, training centers, marketing support, and infrastructure." },
      { q: "कितनी grant मिलती है?", a: "Up to 80% of project cost for common facilities." }
    ],
    relatedSchemes: ["pmegp"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "zed_certification",
    schemeName: "Zero Defect Zero Effect (ZED) Certification Scheme",
    alternativeNames: ["ZED Certification", "ZED"],
    launchYear: 2017,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.zed.msme.gov.in",
    officialGuideline: "https://zed.msme.gov.in/",
    objective: "To promote quality manufacturing and environmental sustainability among MSMEs through ZED certification.",
    overview: "ZED certification assesses MSMEs on quality and environmental parameters. Government provides financial assistance for certification fees.",
    category: "MSME",
    sector: "All manufacturing sectors",
    businessTypes: ["Manufacturing", "Industrial", "Production"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "Manufacturing MSMEs with Udyam registration.",
    whoCannotApply: "Service sector, non-manufacturing, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Subsidy",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: "80% of certification fee",
    maximumFunding: null,
    ownContribution: "20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Quality Management System", "KYC"],
    optionalDocuments: ["ISO Certificate", "Environmental Policy"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply through ZED portal. Submit self-assessment and undergo third-party assessment.",
    approvalProcess: "ZED certifying body assesses and grants certification.",
    fundReleaseProcess: "Subsidy credited to account after certification.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Prepare for quality and environmental assessment.",
    customerBenefits: "Enhanced credibility, market access, government contracts.",
    commonMistakes: "Incomplete self-assessment, poor documentation.",
    commonRejectionReasons: "Non-compliance, low quality standards.",
    consultantNotes: "ZED is a stepping stone for global quality benchmarks.",
    customerPitch: "ZED Certification आपको quality और environment के लिए recognition देता है, 80% fee subsidy के साथ।",
    faq: [
      { q: "ZED Certification के क्या फायदे हैं?", a: "Enhanced credibility, better market access, and preference in government tenders." },
      { q: "कितनी subsidy मिलती है?", a: "80% of certification fee." }
    ],
    relatedSchemes: ["lean_manufacturing"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "design_clinic",
    schemeName: "Design Clinic Scheme",
    alternativeNames: ["Design Clinic", "Design Innovation"],
    launchYear: 2016,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/design-clinic",
    objective: "To improve design capabilities of MSMEs by providing design consultancy at subsidized cost.",
    overview: "Design Clinic scheme provides design intervention and innovation support to MSMEs through expert design consultants. It covers 80% of the consultancy cost.",
    category: "MSME",
    sector: "All sectors",
    businessTypes: ["Manufacturing", "Product Design", "Packaging", "Handicraft"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "MSMEs with Udyam registration, facing design challenges.",
    whoCannotApply: "Non-MSMEs, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "At least 1 year",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Grant",
    loanComponent: null,
    grantComponent: "80% of design consultancy cost",
    subsidyComponent: null,
    maximumFunding: 1000000,
    ownContribution: "20%",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Design Problem Statement", "KYC"],
    optionalDocuments: ["Product Samples", "Customer Feedback"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply through MSME Design Clinic portal. Submit design challenge.",
    approvalProcess: "Expert committee approves based on design potential.",
    fundReleaseProcess: "Grant released to consultant after completion.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Clearly define design problem, scope of work.",
    customerBenefits: "Professional design at low cost, improved product appeal.",
    commonMistakes: "Vague design problem, unrealistic expectations.",
    commonRejectionReasons: "Budget constraints, poor proposal.",
    consultantNotes: "Design clinic can be a game-changer for product-based MSMEs.",
    customerPitch: "Design Clinic scheme आपको product design और packaging के लिए 80% consultancy grant देता है।",
    faq: [
      { q: "Design Clinic में कौन-कौन सी design services cover हैं?", a: "Product design, packaging, graphics, and process design." },
      { q: "कितनी grant मिलती है?", a: "80% of consultancy cost, max ₹10 lakh." }
    ],
    relatedSchemes: ["lean_manufacturing"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "technology_centre_systems",
    schemeName: "Technology Centre Systems Programme",
    alternativeNames: ["TCSP", "Tool Room"],
    launchYear: 2018,
    ministry: "Ministry of MSME",
    department: "MSME Ministry",
    officialPortal: "www.msme.gov.in",
    officialGuideline: "https://msme.gov.in/tcsp",
    objective: "To establish and upgrade technology centres and tool rooms for MSMEs to access advanced manufacturing technologies.",
    overview: "TCSP provides access to advanced CNC machines, 3D printing, and tool room facilities at subsidized rates to MSMEs.",
    category: "Manufacturing",
    sector: "Tooling, Automotive, Aerospace, General Manufacturing",
    businessTypes: ["Tool Room", "Mold Making", "Precision Manufacturing", "Engineering"],
    entityTypes: ["Private Limited", "LLP", "Partnership", "Sole Proprietorship"],
    whoCanApply: "MSMEs requiring advanced manufacturing support.",
    whoCannotApply: "Non-manufacturing, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: null,
    investmentRequirement: null,
    fundingType: "Infrastructure",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: "Subsidized usage charges",
    maximumFunding: null,
    ownContribution: null,
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: null,
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Project Details", "KYC"],
    optionalDocuments: ["Technical Specifications", "CAD Drawings"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration"],
    applicationMode: "Offline",
    applicationProcess: "Apply to nearest Technology Centre / Tool Room.",
    approvalProcess: "Centre approves based on capacity and availability.",
    fundReleaseProcess: "N/A (usage charges apply)",
    processingTimeline: "7-15 days",
    consultantChecklist: "Identify technology needs, prepare CAD drawings.",
    customerBenefits: "Access to advanced machinery at low cost, skilled manpower.",
    commonMistakes: "Not defining clear technical requirements.",
    commonRejectionReasons: "Capacity constraints, incomplete specifications.",
    consultantNotes: "TCSP is a strategic asset for MSMEs in precision manufacturing.",
    customerPitch: "Technology Centre Systems आपको advanced machinery और tool room facilities at subsidized rates provides करते हैं।",
    faq: [
      { q: "TCSP में कौन-कौन सी machines available हैं?", a: "CNC machines, wire cutting, EDM, 3D printing, and precision measurement." },
      { q: "क्या मैं tool room facility का use कर सकता हूँ?", a: "Yes, MSMEs can use these facilities at nominal charges." }
    ],
    relatedSchemes: ["digital_msme"],
    lastUpdated: "2025-01-15"
  },
  // ======================== STATE-LEVEL PLACEHOLDERS (State Startup/MSME Policy) ========================
  {
    id: "state_startup_policy",
    schemeName: "State Startup Policy (Various States)",
    alternativeNames: ["State Startup", "State Innovation Policy"],
    launchYear: 2020,
    ministry: "State Government (Example: Maharashtra, Karnataka, UP)",
    department: "State MSME/IT/Industries Department",
    officialPortal: "www.state.gov.in",
    officialGuideline: "https://state.gov.in/startup-policy",
    objective: "To promote startups within the state through seed funding, incubation, and ease of doing business.",
    overview: "Most states have their own startup policies providing seed funding, co-working space, and regulatory support. Please check your state's specific scheme.",
    category: "Startup",
    sector: "All sectors (state-specific preferences)",
    businessTypes: ["Startup", "Innovation", "Tech", "Product"],
    entityTypes: ["Private Limited", "LLP", "Partnership"],
    whoCanApply: "Startups registered in the state, with innovative business model.",
    whoCannotApply: "Non-innovative businesses, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Less than 5 years (varies by state)",
    turnoverRequirement: "Varies by state",
    investmentRequirement: "Seed funding up to ₹25 lakh (state-dependent)",
    fundingType: "Seed Fund + Grant",
    loanComponent: null,
    grantComponent: "Up to ₹25 lakh (state-dependent)",
    subsidyComponent: null,
    maximumFunding: 2500000,
    ownContribution: "Varies",
    marginMoney: null,
    interestInformation: null,
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: "Not required",
    processingFees: null,
    requiredDocuments: ["State Startup Registration", "Business Plan", "KYC"],
    optionalDocuments: ["Patent/IP Details", "Client List"],
    dprRequired: false,
    quotationRequired: false,
    licensesRequired: ["State Startup Registration"],
    applicationMode: "Online",
    applicationProcess: "Apply through state startup portal. Submit business plan.",
    approvalProcess: "State committee approves based on innovation potential.",
    fundReleaseProcess: "Disbursed in stages or as milestone-based.",
    processingTimeline: "30-60 days",
    consultantChecklist: "Check state-specific eligibility and sector focus.",
    customerBenefits: "State-level recognition, seed funding, networking.",
    commonMistakes: "Not complying with state-specific norms.",
    commonRejectionReasons: "State budget constraints, poor proposal.",
    consultantNotes: "State startup policies vary widely. Please check your state's specific scheme details.",
    customerPitch: "State Startup Policy आपके state में innovation और startup के लिए seed funding और support provides करती है।",
    faq: [
      { q: "State Startup Policy में क्या benefits हैं?", a: "Seed funding, incubation, and regulatory support (varies by state)." },
      { q: "कैसे apply करें?", a: "Through state startup portal or designated department." }
    ],
    relatedSchemes: ["startup_india_seed_fund"],
    lastUpdated: "2025-01-15"
  },
  {
    id: "state_msme_policy",
    schemeName: "State MSME Policy (Various States)",
    alternativeNames: ["State MSME", "State Industrial Policy"],
    launchYear: 2020,
    ministry: "State Government",
    department: "State Industries/MSME Department",
    officialPortal: "www.state.gov.in",
    officialGuideline: "https://state.gov.in/msme-policy",
    objective: "To promote MSMEs at the state level through subsidies, infrastructure, and support.",
    overview: "State MSME policies provide incentives like capital subsidy, interest subvention, and land allotment. Please check your state's specific scheme.",
    category: "MSME",
    sector: "All sectors (state-specific preferences)",
    businessTypes: ["Manufacturing", "Service", "Trade", "Agriculture"],
    entityTypes: ["Sole Proprietorship", "Partnership", "Private Limited", "LLP"],
    whoCanApply: "MSMEs registered in the state.",
    whoCannotApply: "Non-MSMEs, defaulters.",
    minimumAge: 18,
    maximumAge: null,
    businessAgeRequirement: "Any",
    turnoverRequirement: "Varies by state",
    investmentRequirement: "Varies",
    fundingType: "Subsidy + Incentives",
    loanComponent: null,
    grantComponent: null,
    subsidyComponent: "Capital subsidy (varies by state)",
    maximumFunding: null,
    ownContribution: "Varies",
    marginMoney: null,
    interestInformation: "Interest subvention (state-dependent)",
    moratorium: null,
    repaymentTenure: null,
    collateralRequirement: "As per bank",
    processingFees: null,
    requiredDocuments: ["Udyam Registration", "Project Report", "KYC"],
    optionalDocuments: ["Industry License", "Land Allotment Letter"],
    dprRequired: true,
    quotationRequired: false,
    licensesRequired: ["Udyam Registration", "State License"],
    applicationMode: "Online + Offline",
    applicationProcess: "Apply through State MSME department.",
    approvalProcess: "State committee approves based on industry policy.",
    fundReleaseProcess: "Subsidy released after verification.",
    processingTimeline: "30-90 days",
    consultantChecklist: "Check state-specific incentives and eligibility.",
    customerBenefits: "Capital subsidy, interest subvention, land allotment (state-dependent).",
    commonMistakes: "Not complying with state policy norms.",
    commonRejectionReasons: "Budget constraints, incomplete documentation.",
    consultantNotes: "State MSME policies are critical for capital-intensive projects.",
    customerPitch: "State MSME Policy आपके state में capital subsidy और interest subvention provides करती है।",
    faq: [
      { q: "State MSME Policy में क्या benefits हैं?", a: "Capital subsidy, interest subvention, and land allotment (varies by state)." },
      { q: "कैसे apply करें?", a: "Through State Industries/MSME Department." }
    ],
    relatedSchemes: ["pmegp", "mudra_yojana"],
    lastUpdated: "2025-01-15"
  }
];

// ======================== HELPER FUNCTIONS ========================

/**
 * Search for schemes by name, alternative names, or keywords
 * @param {string} query - Search term
 * @param {Array} schemes - (optional) scheme list, defaults to GOVERNMENT_SCHEMES
 * @returns {Array} filtered schemes
 */
function searchScheme(query, schemes = GOVERNMENT_SCHEMES) {
  if (!query || query.trim() === '') return schemes;
  const q = query.toLowerCase().trim();
  return schemes.filter(scheme => {
    const nameMatch = scheme.schemeName.toLowerCase().includes(q);
    const altMatch = scheme.alternativeNames.some(alt => alt.toLowerCase().includes(q));
    const objMatch = scheme.objective.toLowerCase().includes(q);
    const sectorMatch = scheme.sector.toLowerCase().includes(q);
    const catMatch = scheme.category.toLowerCase().includes(q);
    return nameMatch || altMatch || objMatch || sectorMatch || catMatch;
  });
}

/**
 * Search schemes by sector
 * @param {string} sector - e.g., "Agriculture", "MSME", "Startup"
 * @returns {Array} filtered schemes
 */
function searchBySector(sector) {
  if (!sector) return GOVERNMENT_SCHEMES;
  return GOVERNMENT_SCHEMES.filter(s => s.sector.toLowerCase().includes(sector.toLowerCase()));
}

/**
 * Search schemes by business type
 * @param {string} businessType - e.g., "Manufacturing", "Service", "Food Processing"
 * @returns {Array} filtered schemes
 */
function searchByBusinessType(businessType) {
  if (!businessType) return GOVERNMENT_SCHEMES;
  return GOVERNMENT_SCHEMES.filter(s => 
    s.businessTypes.some(bt => bt.toLowerCase().includes(businessType.toLowerCase()))
  );
}

/**
 * Search schemes by entity type (Sole Proprietorship, Private Limited, etc.)
 * @param {string} entityType - e.g., "Private Limited", "Sole Proprietorship"
 * @returns {Array} filtered schemes
 */
function searchByEntity(entityType) {
  if (!entityType) return GOVERNMENT_SCHEMES;
  return GOVERNMENT_SCHEMES.filter(s => 
    s.entityTypes.some(et => et.toLowerCase().includes(entityType.toLowerCase()))
  );
}

/**
 * Search schemes by funding type (Loan, Grant, Subsidy, etc.)
 * @param {string} fundingType - e.g., "Loan", "Grant", "Subsidy"
 * @returns {Array} filtered schemes
 */
function searchByFundingType(fundingType) {
  if (!fundingType) return GOVERNMENT_SCHEMES;
  return GOVERNMENT_SCHEMES.filter(s => 
    s.fundingType.toLowerCase().includes(fundingType.toLowerCase())
  );
}

/**
 * Get complete details of a scheme by ID
 * @param {string} id - scheme ID
 * @returns {Object|null} scheme object or null if not found
 */
function getSchemeDetails(id) {
  return GOVERNMENT_SCHEMES.find(s => s.id === id) || null;
}

/**
 * Get all schemes that an entity is eligible for
 * @param {Object} criteria - { businessType, entityType, sector, age, turnover, cibil }
 * @returns {Array} eligible schemes
 */
function getEligibleSchemes(criteria = {}) {
  const { businessType, entityType, sector, age, turnover } = criteria;
  return GOVERNMENT_SCHEMES.filter(scheme => {
    let eligible = true;
    // Business Type check
    if (businessType) {
      const btMatch = scheme.businessTypes.some(bt => 
        bt.toLowerCase().includes(businessType.toLowerCase())
      );
      if (!btMatch) eligible = false;
    }
    // Entity Type check
    if (entityType && eligible) {
      const etMatch = scheme.entityTypes.some(et => 
        et.toLowerCase().includes(entityType.toLowerCase())
      );
      if (!etMatch) eligible = false;
    }
    // Sector check (rough)
    if (sector && eligible) {
      const sectorMatch = scheme.sector.toLowerCase().includes(sector.toLowerCase());
      if (!sectorMatch) eligible = false;
    }
    // Age check (if scheme has businessAgeRequirement)
    if (age && eligible && scheme.businessAgeRequirement) {
      // Simple check: if age is less than requirement (e.g., "Less than 2 years")
      if (scheme.businessAgeRequirement.includes('Less than')) {
        const maxAge = parseInt(scheme.businessAgeRequirement.match(/\d+/)?.[0] || 0);
        if (maxAge && age > maxAge) eligible = false;
      }
    }
    return eligible;
  });
}

// ======================== EXPORT ========================
// For Node.js / CommonJS
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    GOVERNMENT_SCHEMES,
    searchScheme,
    searchBySector,
    searchByBusinessType,
    searchByEntity,
    searchByFundingType,
    getSchemeDetails,
    getEligibleSchemes
  };
}
// For browser / global usage
else {
  window.GOVERNMENT_SCHEMES = GOVERNMENT_SCHEMES;
  window.searchScheme = searchScheme;
  window.searchBySector = searchBySector;
  window.searchByBusinessType = searchByBusinessType;
  window.searchByEntity = searchByEntity;
  window.searchByFundingType = searchByFundingType;
  window.getSchemeDetails = getSchemeDetails;
  window.getEligibleSchemes = getEligibleSchemes;
}

// ======================== USAGE EXAMPLE ========================
/*
  // Node.js
  const { GOVERNMENT_SCHEMES, searchScheme, getEligibleSchemes } = require('./schemes.js');
  
  // Browser
  console.log(GOVERNMENT_SCHEMES);
  console.log(searchScheme('PMEGP'));
  console.log(getEligibleSchemes({ businessType: 'Manufacturing', entityType: 'Sole Proprietorship' }));
*/
